#!/bin/bash

days=$1
emaCrossJson=$2
shift 2

tmpDir=$(mktemp -d)

for seed in `seq 0 9`
do
	printf "Seed $seed\r"
	robotrade \
		--orders \
		--days $days \
		--summary \
		--seed $seed \
		--verbose 0 \
		--ema-cross $emaCrossJson \
		"$@" \
		>$tmpDir/$seed
done
printf "      \r"
cd $tmpDir
grep Total *

trap "rm -r $tmpDir" EXIT
